---
- name: Verify
  hosts: all

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert VNC service is running
      ansible.builtin.assert:
        that:
          - "'vncserver@{{ vnc_display }}.service' in ansible_facts.services"
          - ansible_facts.services['vncserver@{{ vnc_display }}.service'].state == 'running'
        fail_msg: "VNC service is not running: vncserver@{{ vnc_display }}.service"
        success_msg: "VNC service is running: vncserver@{{ vnc_display }}.service"

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
